dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: OaVEZy5SC2j0pJWVsOsm0AEnHVTI8ookP+rdy/OKGWqozHSWVZ3tEtlXsmLkZKzE8qxPgxYh6a1covC597UXUgp6rL/BhH+0aubXuABjYFqqBmRTGHYbVEZDUEiarIrqW3EjL9ZL4fSEpSvk+Oluba81W0O11pOOy0ObPAEos/f2QjzT/zkchSNMLu9r1/xQ1PIq2n6FmJ4XjpXaUMj1szEk0DygydC6GKULcdhPFVCB1MHUp+feqzEA2eHiRjLiuxXmw0FUxcenemjIZv3MO8eVVTr/vb+P6+BK11q4dnxtLmFHAxVuAMXOqd8MzswlAx+MgeWThUMGUpXLXIjnvVUijXU7wEnkmF8OBI+iAXG3dZR6/QwMLfLnCMvcGMd5B/EDWR5+ppdtjvPw/OZ65kq8ZiNs8SFsoNxmsPeEffvoPGCXmFVWeLC35tfFu6R5cp+uwt37R6qoBFNG+DtCifnZfrS1vyoZDIDf/K3f3TAhG21tGBXy1SvOXbBy/l9d0ad/W9uICd2n5xuNKKcmqrNF16morYMOahltJS3ToWcpZcsNWQZd+Iy6cUvv4Q+kXias+qNq6yy71cdiIAkdRYP7JMnh4Yv+FY5Y8yPWFGseY8fRxf/AVHOx+ME3l9bzIFyQokBk2bz95aeJxw2ka3t8wQKG0RmTNwI8tLz+gnk=
